### ISSUE TITLE
Item Disappears during Snipe, but it still available

### ISSUE THREAD

**Issue by joelgriffiths** [Metric/AnSAddons#10]
While Sniping, I've noticed an Item dings, but then it often disappears from the snipe page before I can click on it (even when the page doesn't change). When I rewind, the item shows up again (then disappears unless I'm quick). I would love to be able to automatically pause updates any time I get a ding (10-20 seconds - possibly configurable), or have it not clear the item unless it gets removed from, or gets pushed past the last page. 

PS. Thank you for this. I was losing my mind losing auctions with TSM because it would reload the item after I clicked on it and before I could buy it.

**Comment by Metric** [comment]
This is already possible in the AnS settings under ESC -> Interface ->
Addons -> AnS.

The option you are looking for is Rescan Time. It defaults to 2 seconds,
but can go up to 30 seconds.

**Comment by joelgriffiths** [comment]
I was wondering about that. Does that adjust the rescan time for every scan or does it only adjust the rescan time if there is something returned in the list? I love the short rescan time, and wouldn’t want to change that unless an item was found. 

I am curious why the item disappears on the rescan though. When I do a reverse scan, I can usually snipe the item. Hopefully it’s not sniping a different item with the wrong price.

**Comment by Metric** [comment]
Right now, it is for every scan. I see what you are getting at. You only
need it to pause if something is found.

Will add this in for 8.3 version of wow as another adjustable setting and
back port to classic version as well. So expect it after 8.3 patch of wow
is released.
