### ISSUE TITLE
Allow disabling AnS modifications to tooltips

### ISSUE THREAD

**Issue by Corbalt** [Metric/AnSAddons#12]
AnS adds auction info to tooltips, but I already have these from another addon and would prefer to be able to disable it.

**Comment by Metric** [comment]
Just disable AnS Auction Data addon. Cause, if you are using data from
another source then the addon is sort of pointless.

**Comment by Corbalt** [comment]
Auctionator only provides a market min variable, but AnsAuctionData has a few more like ans3day that are nice. My ideal setup would be to have the tooltip only contain Auctionator data but to have AnsAuctionData variables available when writing custom filters. Maybe the answer is for me to find a different auction data source than Auctionator, but I like how clean the tooltips are. Auctioneer and TSM fill it with so many numbers.

Thanks for the quick answer though. I'll see if I get used to them.

**Comment by Metric** [comment]
Another option for now, is go into the saved variables Lua of AnS. You will
see a variables that reference the tool tips. Just set the ones you don’t
want to false.
