### ISSUE TITLE
Own commodities break sniper buyout

### ISSUE THREAD

**Issue by jeykey** [Metric/AnSAddons#13]
You can not buy a stack of commodities if it contains your own items within the stack.
Not sure if it is possible to filter out your own items somehow. I tried to add myself to the blacklist but it did not help.

I get following error message:
`AnS: Updated total price of commodities is higher than original total purchase price.`

**Comment by Metric** [comment]
Hmm, interesting. I mean I would think blizz would know to ignore your
stack when trying to purchase from the lowest. Anyway, I will look into
filtering those results out based on your blacklist / current character.
Currently, the blacklist only works on the commodity if it has a single
owner listed. Will try and change it to check when there are multiple
owners.

**Comment by Metric** [comment]
Ah, looks like I missed the new api they included. I wasn't sure what it was fo,r but now I know. In SendSearchQuery(itemKey, sort, separateOwnerItems), if separateOwnerItem is true, then the results will separate out your owned items (account / character related etc), from other auctions. For instance if you have 12 winterkiss posted at the lowest with others, then the search query will return your 12 as a separate result from the other winterkiss that may be listed at the same ppu. Combine that with the other two fields provided by the new search result object: containsOwnerItem and containsAccountItem, we can filter out account and owner items without a blacklist.

However, I will go ahead and update the blacklist to support multiple owner check as well.

I have confirmed the above SendSearchQuery with separate and containsOwnerItem and containsAccountItem check works. I have 3 veiled crystals up at the same price of 751 others. Without using the new separateOwnerItems and contains checks returns 754 veiled crystals. However, with the new check it now only returns the 751 others. Will push this update out shortly.

**Comment by Metric** [comment]
Changes pushed to git and curseforge (may take a few before curseforge approves).

**Comment by jeykey** [comment]
Well that was a quick fix. Thanks!
