### ISSUE TITLE
Classic Error on log in after update

### ISSUE THREAD

**Issue by joelgriffiths** [Metric/AnSAddons#14]
I receive this when logging into Classic with the updates this morning.

Date: 2020-02-04 01:15:30
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AnS\Data\Core.lua line 58:
   attempt to concatenate field 'name' (a nil value)
Debug:
   AnS\Data\Core.lua:58: AddBaseData()
   AnS\Data\Core.lua:100: in main chunk
Locals:
classID = 16
subClassID = nil
parent = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 path = ""
}
inventoryType = nil
name = nil
item = <table> {
 path = ""
 classID = 16
 children = <table> {
 }
}
(*temporary) = ""
(*temporary) = "."
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'name' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AnS, v2.0.5
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=62)

**Comment by Metric** [comment]
Please download version 1.0.7.2 for classic. Version 2 is only for retail
8.3+.

**Comment by joelgriffiths** [comment]
I thought this was the case. Sorry for the bother. I was so excited to see a new release. I get errors in classic when I create a filter for each category, so I was hoping this would fix that. Thank you for all your work. Don't know what I would do without your addon.

**Comment by Metric** [comment]
Would you please open up another issue for the creation of filters bug on
classic. And explain further as to what is happening. I did not know this
was an issue on classic. As I have been primarily focused on 8.3 for the
past few weeks.
