### ISSUE TITLE
Final scan returns results only after 2nd scan

### ISSUE THREAD

**Issue by FoiFoish** [Metric/AnSAddons#15]
Final scan sometimes does not return results. This issue often happens when sniper scans group for the first time.

This video shows this issue.
https://youtu.be/LfZ3HzaUqCQ

**Comment by FoiFoish** [comment]
Checked it again. Even if the group was previously scanned returning new item as result requires 2 final scans.

**Comment by Metric** [comment]
Are you using TUJ or TSM as a data source? Tuj has issues, since it still
uses getiteminfo even for raw item Id. Thus causing the item info cache of
the wow client to reset by the time it gets back to that item. Therefore
tuj returns no results sometimes, because it returns no pricing data for
it.

TSM does not have this issue. Since tsm converts raw item Id to i:1345 etc
and then pulls from their data set without using getiteminfo.

**Comment by FoiFoish** [comment]
I using TSM but this issue appears even with filter like (ppu lt 3000g)

**Comment by Metric** [comment]
How many items are being scanned at one time?

**Comment by FoiFoish** [comment]
Well it appears even with small filter groups like 4 boe (i:175004,i:175005,i:175006,i:175007) same for group with bonus ids.

**Comment by FoiFoish** [comment]
Here is strange thing.  Some items correctly appears after 1st search. For example 1 boe i:175004 with filter (ppu gte 445) 1st search returns only 2 results, 2nd and further scans returns all items. After relog i have same results.

**Comment by Metric** [comment]
How many total items is it processing and are you using the latest version
for 8.3?

**Comment by FoiFoish** [comment]
I am using the latest version and I have noticed this problem for about 2 weeks. I think 300-500 items are processing. But i also have check it with big tmg group (15000) and small (17). Results are the same. And final scan returns 3 item for 1st iteration, 5 for 2nd and further.

**Comment by Metric** [comment]
What is your global percent string?

**Comment by FoiFoish** [comment]
Tried with (dbmarket), (10000g), and without any string. I tried clean install with simple filter, but nothing helps. Here is new screencast with settings.

https://youtu.be/eFbHh3AidJs
This problem does not reproduce for you?

Upd. This also affects items without bonus ids, mounts for example.
Upd2. If i manually enter to the group from "Buy" tab, items from this group correctly appears after 1st scan.

**Comment by Metric** [comment]
I believe I found the issue that is causing this.

**Comment by Metric** [comment]
If you would, please pull down the latest from github and test to see if the latest changes fixes this issue. Please report back whether the changes or good or not.

That way, I can push it out to everyone over curseforge if they are.

Thanks

**Comment by FoiFoish** [comment]
Looks great, twice faster than previous version. After short tests I don't see any problems for me so far. If i find something I will report. Thank you for fix!
