### ISSUE TITLE
Exception when adding filters into 

### ISSUE THREAD

**Issue by joelgriffiths** [Metric/AnSAddons#16]
I receive this error in Classic anytime I add a filter string to a group. In this case, I added "percent lte 80 and iLevel gte 35" to the Container group, but it seems to error whenever I add anything in the Group Filters. My global filter in this case is "tujdays ~= 252 and ppu gte 1g and ilevel gte 40 and ((stacksize gt 1 and percent lte 70 and ppu lte 3g) or (stacksize == 1 and percent lte 40))"

I added some debugging code, and it doesn't appear to be related to containers at all. so I'm quite confused.

I'm sure this is a user error, and I hate to keep posting issues considering how useful this code is, but I don't know where else to go.

`Date: 2020-02-05 16:04:06
ID: 1
Error occured in: Global
Count: 1
Message: [string "    return function(sources, ops)..."] line 24:
   attempt to compare number with nil
Debug:
   (tail call): ?
   [C]: ?
   [string "    return function(sources, ops)..."]:24: fn()
   AnS\Core\Sources.lua:422: Query()
   AnS\Core\Auction\Filter.lua:493: IsValid()
   AnS\Core\Auction\Query.lua:789: Capture()
   AnsAuctionSnipe\AuctionSnipe.lua:382: OnAuctionUpdate()
   AnsAuctionSnipe\AuctionSnipe.lua:341: EventHandler()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AnS, v1.0.6.8
  AnsAuctionData, v1.0.0
  AnsAuctions, v1.0.4
  AnsAuctionSnipe, v1.0.6.4
  ArkInventory, v30916
  ArkInventoryRules, v20000
  ArkInventorySearch, v20000
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasTransportation, vv1.46.03.11303.00
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatBootyBayGazette, v1.13.2.1
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BootyBayGazette, v6.1.20200203
  Clique, vv1.0.3-classic
  DBMCore, v1.13.30
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Dejunk, v8.3.0
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.20
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  ExtendedCharacterStats, v2.1.4
  FishingBuddy, v0.7.3 Beta 2
  GatherMate2, v1.45.5
  GearQuipper, v30
  HHTD, v2.4.9.4
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  Mapster, v1.8.5
  oRA3, vv4-classic
  Questie, v5.6.0
  RealMobHealth, v2.18
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SmartBuff, v1.13.2d
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomTom, vv11303-1.0.9
  TradeSkillMaster, vv4.9.22
  TradeSkillMasterAppHelper, vv4.0.7
  WeakAuras, v2.16.2
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=777)
`

**Comment by joelgriffiths** [comment]
I added debugging code and was able to correlate the use of iLevel with the error. It's supposed to be ilevel. Case matters apparently. Sorry for the bother.

**Comment by Metric** [comment]
If that quoted string is accurate, then make sure ilevel is all Lower case.
All built in variables are always lower case in the filter string. The only
variables that can be any case is user custom ones, if I remember
correctly.

Because this does indeed look like a user error with the filter string.
Where the specified variable name is incorrect thus the trying to compare
number to nil.
