### ISSUE TITLE
Addon wont send Ding Sound and WOW Taskicon wont flash like tsm when it found smth.

### ISSUE THREAD

**Issue by donyil** [Metric/AnSAddons#18]
Hey im very happy with AnS Sniper but it does not make a Sound when it found something and wont flash taskbar when wow is in background.
The Ding Sound setting is on. 
Using wow classic.

**Comment by Metric** [comment]
Please use the experimental branch on GitHub if you want these features
right away. As this is already implemented and fixed in it. Experimental is
quite stable.
