### ISSUE TITLE
Classic Error.

### ISSUE THREAD

**Issue by Havenloft** [Metric/AnSAddons#21]
2085x AnsAuctions\AnsAuctions-1.0.4.lua:53: attempt to index upvalue 'AuctionsBuy' (a nil value)
AnsAuctions\AnsAuctions-1.0.4.lua:53: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
self = <table> {
 BuyAuction = <function> defined @AnsAuctions\AnsAuctions.lua:88
 StartDataScan = <function> defined @AnsAuctions\AnsAuctions.lua:100
 OnMoneyUpdate = <function> defined @AnsAuctions\AnsAuctions.lua:79
 StartBuyScan = <function> defined @AnsAuctions\AnsAuctions.lua:92
 OnMultisellUpdate = <function> defined @AnsAuctions\AnsAuctions.lua:71
 __index = <table> {
 }
 RegisterEvents = <function> defined @AnsAuctions\AnsAuctions.lua:14
 EventHandler = <function> defined @AnsAuctions\AnsAuctions.lua:25
 StopDataScan = <function> defined @AnsAuctions\AnsAuctions.lua:104
 OnBagUpdate = <function> defined @AnsAuctions\AnsAuctions.lua:75
 PostAuction = <function> defined @AnsAuctions\AnsAuctions.lua:84
 StopBuyScan = <function> defined @AnsAuctions\AnsAuctions.lua:96
 OnAuctionUpdate = <function> defined @AnsAuctions\AnsAuctions.lua:65
 OnAddonLoaded = <function> defined @AnsAuctions\AnsAuctions.lua:39
 OnAuctionHouseShow = <function> defined @AnsAuctions\AnsAuctions.lua:48
 OnUpdate = <function> defined @AnsAuctions\AnsAuctions.lua:52
 OnAuctionHouseClosed = <function> defined @AnsAuctions\AnsAuctions.lua:58
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'AuctionsBuy' (a nil value)"
AuctionsBuy = nil
AuctionsSell = nil
AuctionData = nil

**Comment by Metric** [comment]
AnsAuctions has been deprecated. It will not be updated any further at this point. It will be replaced with shopping operations eventually.
