### ISSUE TITLE
Dragonflight issues

### ISSUE THREAD

**Issue by Smallinger** [Metric/AnSAddons#24]
The pre-patch of Dragonflight killed this addon.

**Comment by Metric** [comment]
Please see: https://github.com/Metric/AnSAddons/releases/tag/2.2.7beta7

And let me know if this fixes issues as expected.

**Comment by Smallinger** [comment]
Hey first of all Thanks for you hard Work!

The Problem ist the Sniper function are not working, i type a name in the Name FIlter, give it a MAX PPU an press Start,
the only thing that i can see is "Querying... "and "Filtering Groupe 1 of 1" in fast switching and i got null resualts, i have the same if i type nothing in it.

**Comment by Smallinger** [comment]
Oh wow, ok now i can say this was becuse my text language ingame was in German and i use the german word for "Desolate Leather" "Gramleder" after change my game to English and use "Desolate Leather" it work, i hope you can fix it so it is working with german text again or better with item ids.

**Comment by Metric** [comment]
Strange, considering it would use what is ever return in the Auction Item Link provided by Blizzard. It does do item ids via groups just fine. So, you should use groups if you want precise item id filtering.

**Comment by Smallinger** [comment]
yeah i think this was a blizzard problem, after the latest hotfix from blizzard all is working normal ¯\_(ツ)_/¯
