### ISSUE TITLE
Usage: PostAuction(minBid, buyoutPrice, runTime, count)

### ISSUE THREAD

**Issue by penguinsane** [Metric/AnSAddons#4]
Getting this error when attempting to use AnsSell. It happens after I select an item to sell, post one, and then select a different item. It won't let me post more than one item at a time... I have to post an item, close the auction window, re-open, post another, etc. 

```
12x Usage: PostAuction(minBid, buyoutPrice, runTime, count)
[C]: ?
[C]: in function `PostAuction'
AnsAuctions\Modules\Sell.lua:397: in function `Sell'
AnsAuctions\Modules\Sell.lua:284: in function `PostSelected'
AnsAuctions\AnsAuctions-1.0.1.lua:56: in function `PostAuction'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = 2146917
(*temporary) = 2146917
(*temporary) = nil
(*temporary) = 1
(*temporary) = 1
```

**Comment by Metric** [comment]
Someone else was experiencing this same issue. But they never provided an
error log. However, for some reason after they rebooted it worked again.
Not sure why.

What item were you posting before this error happened? And what item were
you trying to post that threw this error? This will help to know so I can
try and replicate.

**Comment by Metric** [comment]
Hmm, yes it looks like they changed the function format for PostAuction It used to be: PostAuction(minBid, buyoutPrice, runTime, stackSize, numStacks). It appears they have combined the total item count into one variable. Will get this fixed ASAP.

**Comment by Metric** [comment]
Just pushed a fixed to github and curseforge. It appears it was a twofold problem. One was the api change for the postauctions function and another seems to be blizzard broke the UIDropDownMenu_GetSelectedID. The UIDropDownMenu_GetSelectedID was returning nil for some reason when you had 48 hours selected in the time drop down (After you posted once). Switched it to UIDropDownMenu_GetSelectedValue which appears to work properly 100% of the time.

**Comment by penguinsane** [comment]
It didn't matter what items I was posting, it seemed to happen with everything. I downloaded the update and everything works great. Thanks so much for the fast response!
