### ISSUE TITLE
New feature suggestion: Items ID blacklist

### ISSUE THREAD

**Issue by Gargauth** [Metric/AnSAddons#5]
Hello! First off - amazing addon - thank you!

I like broad filtering for categories and subcategories - like `weapons` and `armor`, `tradeskill` etc.. Sometimes I would like to exclude few of the items from matching these broad filters. After reading documentation, there is no ItemID variable I could use in filter string. It would be very helpful if there was option to exclude certain IDs - either by having separate field that would accept parameters like `i:1234567`, or even make use of current "Item or Pet IDs" field but prepend/append modifier like `!` in front of ID (like `i:12345!` to indicate negative filter)

Thank you for consideration.

**Comment by Metric** [comment]
Sorry for the late reply, but I had started to implement this. However, I have since been side tracked with a deadline for work. I probably won't get this out until after April 1st.

**Comment by Metric** [comment]
This has technically been implemented for the 8.3 version, but still needs to be back ported to the classic version.
