### ISSUE TITLE
easy filters not working in classic (german client)

### ISSUE THREAD

**Issue by Stef4fun** [Metric/AnSAddons#6]
Hi,
thx for the great addon, I really would like to use it but some filter strings dont work:
Working e.g:
   Item: i:4306
   Filter String: ppu lt 1s85c
Also the preset groups work

Not working filter strings without itemids (arbitrary values for getting results):
ppu lt vendorsell * 2000g
ppu lt 2000g
vendorsell < 2000g
dbmarket < 2000g

I have the impression that the usage of all strings in the filter does not work.
I dont have TUJ price sources because I could not find it for classic.
But I have TSM4.
Do you have any idea about the reason?
Are my filter strings wrong or would can it be?

Thanks again

**Comment by Metric** [comment]
At the moment, filter strings for filter groups only apply if there are item ids in that filter group or sub groups.

I just tested all the provided filter strings in the global filter string, and they do work on classic. So for the moment for general filter strings such as those, where no item id is required, use them in the global filter string. Filter strings in filters are not based on the global filter string. The only time a filter uses the global filter string is if no filter string is provided for that filter or parent filter.

**Comment by Stef4fun** [comment]
Ok thank you
