### ISSUE TITLE
global filter string

### ISSUE THREAD

**Issue by tribled** [Metric/AnSAddons#7]
Hi, THX for ans! For me its more usefull than tsm! 

I have tried a global filter like:

ifgte(quality, 2, ansminprice * ifgt(ansminprice, 2500g, 40, ifgt(ansminprice, 500g, 30, ifgt(ansminprice, 100g, 25, ifgt(ansminprice, 50g, 20, ifgt(ansminprice, 10g, 15, ifgt(ansminprice, 5g, 13, ifgt(ansminprice, 30s, 11, 0)))))))
 / 100)

but it doesnt work - what is wrong? ansminprice  is already a custom var and is successfully working as global percent string. 
if the global filter is set with the string above (remaining fields are empty), it returns wrong results.

greetings dan

**Comment by Metric** [comment]
You need to compare the final result to something. The final result should
be a Boolean value of either true or false.

From my estimation you would want to compare that result to percent or ppu.

It also appears you are forgetting the secondary result value for that
ifgte. Right now, it would be returning a nil value and throwing an error
if you had ui errors turned on.

Also you will want to use the % after your percent numbers, so you don’t
have to do a / 100.
