### ISSUE TITLE
Client does not recover after double clicking on an item which is already gone

### ISSUE THREAD

**Issue by Stef4fun** [Metric/AnSAddons#8]
Running the sniper module with some filters with itemIds and easy strings.
After a while an item pops up which meets the conditions.
Then it e.g. shows that 1 stack of xyz.
Then I double click it to buy it but someone else was faster then me and the item is gone.
Error message "Item not available anymore" (or similar) is shown on the screen.
Then the sniper wants to query the next page, but it never resolves.
Stucks in "Waiting to Query..."
Stop and Start does not resolve it (It keeps telling: "Page: 0 - Starting ...")
only /reload does solve it.

Do you have any idea about the root cause?

**Comment by Metric** [comment]
This has been a known issue for a while. I have yet to track down what
causes it exactly. I cannot say what makes it lose its known state and get
confused. Could be due to waiting for player money update, but it does not
happen when it fails. Probably should put a timer on it to clear that one
state if it doesn’t after a certain time.

**Comment by Stef4fun** [comment]
Small update:
It even happened to me after double clicking the item and getting it.
Then the above list was not updated anymore and the scan stuck in the same way like written above.
Also other regular searches on the AH did not work anymore after the issue happened.

**Comment by Metric** [comment]
This appears to be an issue, where in trying to buy something, while it is waiting for a query response from server, confuses the actual WoW client UI wise, and thus a /reload fixes it. However, the first issue that you experienced is definitely a fault on my part for not anticipating a failure properly when it came to waiting for player money change. Will try to get these fixes in this weekend for it.

**Comment by Metric** [comment]
This issue has now been fixed in latest release on curseforge and code uploaded to git.

**Comment by Stef4fun** [comment]
Great, thank you, I will test it a bit.
