### ISSUE TITLE
[Classic] Horde vs Alliance AH

### ISSUE THREAD

**Issue by tjesp** [Metric/AnSAddons#9]
Hi, I play on horde on a server. I recently made an alliance character on the same server. On classic there are separate auction houses.

I just did my first scan on alliance and some of the data seems strange like ansmarket and ansmin. I wonder if AnS differs between alliance and horde auction house?

**Comment by Metric** [comment]
Ooh, I don’t think I took that into account for classic. Pretty sure it is
realm only at the moment. Will definitely need to add that in for classic.
I forgot, that the AH on classic could differ between horde and alliance by
quite a bit.
